### ISSUE TITLE
 Syntax Node immunization/effectiveTime

### ISSUE THREAD

**Issue by swmuir** [MDMI/cda2mdmi#1]
Syntax Node immunization/effectiveTime is set to datatype of dateTime. This is ok.  The issue is there can be a @low and @high attribute.  Maybe not in this case, but we will need to be able to populate both.  In the Referent Index, the pattern will be Business Elements for StartDate and EndDate with datatypes of dateTime.  I haven’t gotten to refactor the Immunization dates yet.

**Comment by KenLord** [comment]
From the 9/4 generated CCDA map. The Semantic Element in allergysection.observation.effective time has a datatype of string.  It should be datetime, except that there is a @low attribute and a @high attribute. I think the correct solution is:
- add dateRange as a datatype and you should be able to pick this up automatically.  
- Have the Expert mapping map low to StartDate and high to EndDate.
- Enhance the JSON interface from the Expert Mapper to be able to assign SemanticElement.@low to BusinessElement with primitive datatype of datetime.

I think we can do step 1 right now.  The step 2 and 3 are enhancements.

**Comment by swmuir** [comment]
Revisit when support for annotation

**Comment by swmuir** [comment]
This has been addressed
