### ISSUE TITLE
 Static Variables: 

### ISSUE THREAD

**Issue by swmuir** [MDMI/cda2mdmi#2]
Static Variables: TypeCode, ClassCode, StatusCode etc. need to be addressed when writing out the target file in order to pass validation.
o   No templateID in immunizationentry.
-          MoodCode needs to show up because the Immunization Activity could be an event or an order. Same holds, unfortunately, for negationIND. We can set negationIND to TRUE for now. This is where having Local and Normal for Doug would be very helpful.
-          Missing (both syntax and semantic) are administrationUnitCode, repeatNumber, and approachSiteCode. It may be because the cardinality is 0.1, however we do have routeCode and others elements with a cardinality of 0.1.
-          In Patientinstructions, again we need (for validation) to have moodCode, templateID, statusCode, and ClassCode.

**Comment by swmuir** [comment]
I send the email i can not add the xmi file

**Comment by KenLord** [comment]
I do not see any typeCode assignments. With that, I think we can close this issue.

I will enter a new issue and assign it to me.  It has to do with the following pattern: if the moodCode is not static (e.g. medication activity), its value is implicit in the Semantic to Business Element mapping and the Semantic Tree in which it is in.  There needs to be a rule somewhere.

**Comment by swmuir** [comment]
Ken to test

**Comment by swmuir** [comment]
Based on Mood Code constraint in MDHT - need to create multiple semantic element based on the mood code - look at immunization

**Comment by swmuir** [comment]
Duplicate

**Comment by swmuir** [comment]
This is duplicate
