### ISSUE TITLE
Missing Mappings for administrationUnitCode, repeatNumber, and approachSiteCode

### ISSUE THREAD

**Issue by swmuir** [MDMI/cda2mdmi#3]
Missing (both syntax and semantic) are administrationUnitCode, repeatNumber, and approachSiteCode. It may be because the cardinality is 0.1, however we do have routeCode and others elements with a cardinality of 0.1.

**Comment by swmuir** [comment]
This is working with the latest releases - I see all three under CONSOL_MEDICATIONSECTION_MEDICATION

**Comment by KenLord** [comment]
I will close this as those semantic elements do appear.
