### ISSUE TITLE
Duplicate syntax nodes in General Header Section

### ISSUE THREAD

**Issue by KenLord** [MDMI/cda2mdmi#4]
The root syntax node in the CCDA map sent 9/2 at 12:20 has two child syntax nodes that have the same name.  Examples are there are two code syntax nodes ( locations of realmCode and  and code. there is another syntax node with the location of realmCode), two languageCode syntax nodes (both with locations of realmCode), and two author syntax nodes (the first author syntax node and its children is very good and the second is not).

**Comment by swmuir** [comment]
This was an issue in the mdht routine;  updated and committed a fix

**Comment by KenLord** [comment]
good job.
