### ISSUE TITLE
CCDA generated Map: AssignedAuthorPersonName datatype and syntax node

### ISSUE THREAD

**Issue by KenLord** [MDMI/cda2mdmi#5]
In ccdaMap generated 9/2, in general header , author, assigned Author, assignedPerson, there is a syntax node of name that is of type LST. It is associated with a Semantic Element that has a datatype of PersonName, which is correct.  The syntax node of name with type LST should be of type Bag and should have child syntax nodes that are the attributes of the datatype PersonName.

**Comment by swmuir** [comment]
Fixed

**Comment by KenLord** [comment]
Closed
