### ISSUE TITLE
General Issue: Semantic Elements of type Container

### ISSUE THREAD

**Issue by KenLord** [MDMI/cda2mdmi#6]
General Rule:
In the Semantic Element Tree, the only parent of a Semantic Element can be a Semantic Element of datatype Container of type Normal. A normal Semantic Element of type Container must have an associated syntax node that has cardinality of >1.  If it is recognized that a syntax node has a cardinality of 1 and does not have a value (it is a container), then there should be no Semantic Element created for this syntax node. The exception to this rule is the Root variable.

Example: The syntax node of Author is >1. Therefore it has a Semantic Element called Author with a datatype of Container and of type Normal.  Author has a child syntax node call AssignedAuthor.  AssignedAuthor does not have values (it is a container).  Therefore AssignedAuthor does not have an associate semantic element. The syntax node of addr is a child of the syntax node AssignedAuthor. The semantic element created for this node is correct (datatype address).  The semantic parent of addr should be Author.

**Comment by swmuir** [comment]
The AssignedAuthor can have values specifically address and telecom - see below and is required
So while we do need to understand the container/type this is not the case

We do have an issue of getting two authors in the document definition


		<assignedAuthor classCode="ASSIGNED">
			<id nullFlavor="NI"/>
		<telecom use="WP" value="tel:(555) 555-1010"/>
				<addr use="WP">
					<streetAddressLine>4000 Hospital Dr.</streetAddressLine>
					<city>Portland</city>
					<state>OR</state>
					<postalCode>97005-    </postalCode>
					<country>US</country>
				</addr>
			<assignedAuthoringDevice>
				<manufacturerModelName>Cerner Corporation</manufacturerModelName>
				<softwareName>Millennium Clinical Document Generator</softwareName>
			</assignedAuthoringDevice>
		</assignedAuthor>

**Comment by KenLord** [comment]
Sean,

I believe we can handle your concerns.

The container above assignedAuthor is the "Semantic Container" determining
if there are more than one author.  As to assignedAuthor being an
organization and person versus an organization/device, Is this the case?
Or is it that it can be a person and a device? The second case is easy.
The first case requires a choice. There is a way to handle this and Gabriel
has a test case.

Ken

**Comment by swmuir** [comment]
Fixed - I now check to see if the class is a rim "Role" as in act participation role entity
I am not sure that is 100% correct but it is a start

**Comment by KenLord** [comment]
I think the comment associated with Issue 7 applies to this issue as well.

**Comment by swmuir** [comment]
Ken to verify
