### ISSUE TITLE
General Pattern: Local versus Normal

### ISSUE THREAD

**Issue by KenLord** [MDMI/cda2mdmi#7]
Requirement:  Doug / IBM need to only map Semantic Elements of type NORMAL.

Rules for determining whether a Semantic Element is NORMAL or LOCAL. Present Scope is limited to UML models in MDHT.

If an attribute in the model has a CDA datatype (versus an object / class) and the value is constrained to a static value (we are doing a lot of this logic already), then the Semantic Element associated with this attribute should be of type LOCAL. All other Semantic Elements associated with an attribute in the UML model having a CDA datatype should be of type NORMAL.

From a previous issue, we already have rules for containers (objects/classes).

**Comment by swmuir** [comment]
Was there a specific one that is not correct - i am setting all the defaulted to LOCAL

**Comment by KenLord** [comment]
There are no NORMAL Semantic Elements in the map.  By assigning LOCAL or NORMAL, Doug knows what to map and what to ignore.

**Comment by swmuir** [comment]
Updated to default to normal

**Comment by KenLord** [comment]
Looks much better.... however when you get down into lower elements of the syntax tree, it still is not quite right.  For example, in allergysection.act.observation.severty container, it has a cardinality of 1 (correct) and has a semantic element.  It should not have a semantic element.  Additionally, it has has a children (e.g., value) that do have assigned semantic elements (correct), but these semantic elements do not have the correct semantic parent.  For value, its parent should be section.act.observation and instead its parent is section.act.observation.severity which should not exist.

**Comment by swmuir** [comment]
If entryRelationship has upper bound of 1 - do not create semantic container (or element)

**Comment by swmuir** [comment]
Added additional logic to determine local entry relationships
